feat: katib-db-manager rock
canonical/katib-rocks pull request #15
Opened 2023-07-18 18:15 UTC by i-chvets

Katib ROCKs are part of main epic for building secure images using ROCKs. katib-db-manager ROCK is managed by katib-controller charm. Charm's integration tests should be re-used to test functionality of this ROCK.

Summary of changes:
- Initial version of the ROCK.
- Created rockcraft file for katib-db-manager ROCK. ROCK is built and limited manual testing is done.

Manual test:
```
docker run katib-db-manager:v0.15.0_22.04_1 exec /app/katib-db-manager
2023-07-18T18:13:48.097Z [pebble] Started daemon.
2023-07-18T18:13:48.197Z [pebble] POST /v1/exec 98.854491ms 202
2023-07-18T18:13:48.198Z [pebble] GET /v1/tasks/1/websocket/control 152.171µs 200
2023-07-18T18:13:48.199Z [pebble] GET /v1/tasks/1/websocket/stdio 104.532µs 200
2023-07-18T18:13:48.199Z [pebble] GET /v1/tasks/1/websocket/stderr 75.966µs 200
F0718 18:13:48.205851      16 main.go:100] DB_NAME env is not set. Exiting
2023-07-18T18:13:48.315Z [pebble] GET /v1/changes/1/wait 115.753682ms 200
```

2023-07-18 20:31 UTC, i-chvets commented on katib-db-manager/rockcraft.yaml
> +
Refactor the above health check into its own part.

2023-07-19 13:59 UTC, i-chvets commented on katib-db-manager/rockcraft.yaml
> +
Done.

2023-07-19 15:38 UTC, SamirPS requested changes

2023-07-19 15:38 UTC, SamirPS commented on katib-db-manager/rockcraft.yaml
> +    command: "/app/katib-db-manager"
I think using a working-dir in each of your ROCKs is a good practice if possible

2023-07-27 16:00 UTC, i-chvets commented
@SamirPS updated. Please review.

2023-07-27 16:58 UTC, SamirPS approved these changes

2023-07-27 17:59 UTC, ca-scribner approved these changes

2023-07-27 18:00 UTC, merged