feat: suggestion-hyperopt rock
canonical/katib-rocks pull request #16
Opened 2023-07-18 20:21 UTC by i-chvets

Katib ROCKs are part of main epic for building secure images using ROCKs.

ROCK for Katib suggestion-hyperopt is part of katib-config.

Since configuration is provided when this container is ran in the pod it is expected to fail when running manually. Howvever, it is enough to ensure that service is being started.

Summary of changes:
- Initial version of suggestion-hyperopt ROCK.

```
docker run suggestion-hyperopt:v0.15.0_22.04_1 exec bash -c 'export PYTHONPATH="/usr/local/lib/python3.10/dist-packages/:/opt/katib:/opt/katib/pkg/apis/manager/v1beta1/python:/opt/katib/pkg/apis/manager/health/python" && python3 /opt/katib/cmd/suggestion/hyperopt/v1beta1/main.py'
2023-07-18T20:19:11.781Z [pebble] Started daemon.
2023-07-18T20:19:11.798Z [pebble] POST /v1/exec 16.306833ms 202
2023-07-18T20:19:11.814Z [pebble] GET /v1/tasks/1/websocket/control 15.128011ms 200
2023-07-18T20:19:11.815Z [pebble] GET /v1/tasks/1/websocket/stdio 136.637µs 200
2023-07-18T20:19:11.815Z [pebble] GET /v1/tasks/1/websocket/stderr 204.196µs 200
INFO:hyperopt.utils:Failed to load cloudpickle, try installing cloudpickle via "pip install cloudpickle" for enhanced pickling support.
INFO:hyperopt.fmin:Failed to load cloudpickle, try installing cloudpickle via "pip install cloudpickle" for enhanced pickling support.
```

2023-07-19 15:37 UTC, SamirPS requested changes

2023-07-19 15:37 UTC, SamirPS commented on suggestion-hyperopt/rockcraft.yaml
> +  suggestion-hyperopt:
Same thing with working dir

2023-07-19 15:37 UTC, SamirPS commented on suggestion-hyperopt/rockcraft.yaml
> +        craftctl default
i don't think this is needed

2023-07-27 15:00 UTC, i-chvets commented
@SamirPS Ready for final review.

2023-07-27 15:20 UTC, SamirPS approved these changes

2023-07-27 15:40 UTC, ca-scribner approved these changes

2023-07-27 15:47 UTC, merged